version: '3'

services:
  nginx:
    build: ./srcs/requirements/nginx/.
    volumes:
      - ./volumes/WordPress:/var/www/html
    ports:
      - 8080:80
    networks:
      - jayoon
    restart: always
    tty: true
volumes:
  volumes:
networks:
  jayoon:
    driver: bridge
  