version: '3'

services:
  mysql:
    build: ./requirements/mysql/.
    volumes:
      - ./volumes/DB:/var/lib/mysql
    env_file: .env
    networks:
      - jayoon
    restart: always
    tty: true

  wordpress:
    build: ./requirements/wordpress/.
    volumes:
      - ./volumes/WordPress:/var/www/html
    depends_on:
      - mysql
    env_file: .env
    networks:
      - jayoon
    restart: always
    tty: true

  nginx:
    build: ./requirements/nginx/.
    volumes:
      - ./volumes/WordPress:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 8080:80
    networks:
      - jayoon
    restart: always
    tty: true
    
volumes:
  WordPress:
  DB:
networks:
  jayoon:
    driver: bridge
  