version: '3'

services:
  nginx:
    build: ./requirements/nginx/.
    volumes:
      - ./volumes/WordPress:/var/www/html
    depends_on:
      - wordpress
    ports:
      - 8080:80
    networks:
      - jayoon
    restart: always
    tty: true
  wordpress:
    build: ./requirements/wordpress/.
    volumes:
      - ./volumes/WordPress:/var/www/html
    networks:
      - jayoon
    restart: always
    tty: true

volumes:
  volumes:
networks:
  jayoon:
    driver: bridge
  