version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: jayoon
      MYSQL_PASSWORD: password
    restart: always

  wordpress:
    depends_on:
      - mysql
    image: wordpress:latest
    ports:
      - "8000:80"
    volumes:
      - ./wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: jayoon
      WORDPRESS_DB_PASSWORD: password
    restart: always

volumes:
  mysql_data:
  wordpress_data:
